 

remote <IP SERVER> <PORT> udp4

 

resolv-retry infinite

 

client

dev tun

nobind

 

verb 3

auth-nocache

user nobody

group nogroup

 

auth SHA512

persist-key

persist-tun

cipher AES-256-GCM

tls-client

remote-cert-eku "TLS Web Server Authentication"

 

ca ca.crt

cert client.crt

key client.key

tls-crypt tc.key

dh none

 

