
ARG registry
FROM $registry/labtainer.network

ARG lab
ARG labdir
ARG imagedir
ARG user_name
ARG password
ARG apt_source
ARG version
LABEL version=$version
ENV APT_SOURCE $apt_source
RUN /usr/bin/apt-source.sh

# Install dependencies
ENV DEBIAN_FRONTEND noninteractive
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
#RUN echo 'wireshark-common  wireshark-common/install-setuid boolean true' | debconf-set-selections
RUN apt-get update && apt-get install -y \
#   snort dnsutils wireshark \
    git \
    ruby \
    build-essential 
#RUN chmod a+x /usr/bin/dumpcap
# Install the system files found in the _system directory
#
ADD $labdir/$imagedir/sys_tar/sys.tar /
ADD $labdir/sys_$lab.tar.gz /

#Create a non-root user
RUN useradd -ms /bin/bash $user_name
RUN echo "$user_name:$password" | chpasswd
RUN adduser $user_name sudo


USER $user_name
ENV HOME /home/$user_name
#
# Install files in the user home directory
ADD $labdir/$imagedir/home_tar/home.tar $HOME

#Clone dnscat2 repository and build dnscat2 client
RUN git clone https://github.com/iagox86/dnscat2.git $HOME/dnscat2
RUN cd $HOME/dnscat2/client && make

# remove after docker fixes problem with empty tars
RUN rm -f $HOME/home.tar
ADD $labdir/$lab.tar.gz $HOME
#
#  The first thing that executes on the container.
#
USER root
CMD ["/bin/bash", "-c", "exec /sbin/init --log-target=journal 3>&1"]

