

### Labtainer Dockerfile cho ftp-server

# 

ARG registry
FROM $registry/labtainer.network

ARG lab
ARG labdir
ARG imagedir
ARG user_name
ARG password
ARG apt_source
ARG version
LABEL version=$version
ENV APT_SOURCE $apt_source
RUN /usr/bin/apt-source.sh

RUN apt-get update && apt-get install -y vsftpd

RUN useradd -ms /bin/bash student && echo "student:123456" | chpasswd
RUN mkdir -p /var/run/vsftpd/empty && chmod 755 /var/run/vsftpd/empty


COPY vsftpd.conf /etc/vsftpd.conf

RUN echo "This is a test file for FTP Lab" > /home/student/test.txt \
&& chown student:student /home/student/test.txt



CMD service rsyslog start && /usr/sbin/vsftpd /etc/vsftpd.conf -obackground=NO
