# ---- Base ----
ARG registry=labtainers
FROM ${registry}/labtainer.network.ssh2

# ---- Labtainer args/labels ----
ARG lab
ARG labdir
ARG imagedir
ARG user_name
ARG password
ARG apt_source
ARG version
LABEL version="${version}"
ENV APT_SOURCE="${apt_source}" \
    DEBIAN_FRONTEND=noninteractive

RUN /usr/bin/apt-source.sh

# ---- Tools ----
RUN apt-get update -y && apt-get install -y --no-install-recommends \
      curl wget hydra && \
    rm -rf /var/lib/apt/lists/*

# Lấy wordlist từ GitHub phải dùng raw.githubusercontent.com
RUN wget -O /opt/pass.txt \
  https://raw.githubusercontent.com/duyet/bruteforce-database/master/8-more-passwords.txt

# ---- Labtainer payloads (system) ----
ADD ${labdir}/${imagedir}/sys_tar/sys.tar /
ADD ${labdir}/sys_${lab}.tar.gz /

# ---- User ----
RUN useradd -ms /bin/bash "${user_name}" && \
    echo "${user_name}:${password}" | chpasswd && \
    adduser "${user_name}" sudo

# ---- User payloads ----
USER ${user_name}
ENV HOME="/home/${user_name}"
ADD ${labdir}/${imagedir}/home_tar/home.tar ${HOME}
RUN rm -f ${HOME}/home.tar
ADD ${labdir}/${lab}.tar.gz ${HOME}

# ---- Entrypoint ----
USER root
CMD ["/bin/bash", "-c", "exec /sbin/init --log-target=journal 3>&1"]

