zone "." {
    type master;
    file "/var/cache/bind/root.zone";
};
zone "com" {
   type master;
   file "/var/cache/bind/c2c.com.zone";
};
zone "19.10.10.in-addr.arpa" {
   type master;
   file "/var/cache/bind/10.10.19.0";
};


