# Labtainer Dockerfile
ARG registry
FROM $registry/labtainer.network
ARG lab
ARG labdir
ARG imagedir
ARG user_name
ARG password
ARG apt_source
ARG version
LABEL version=$version
ENV APT_SOURCE $apt_source
RUN /usr/bin/apt-source.sh


RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        traceroute \
        quagga \
        quagga-doc && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Tạo thư mục cấu hình cho Quagga
RUN mkdir -p /etc/quagga && \
    chown quagga:quagga /etc/quagga && \
    chmod 755 /etc/quagga

# Enable zebra và ospfd
RUN echo "zebra=yes" >> /etc/quagga/daemons && \
    echo "ospfd=yes" >> /etc/quagga/daemons

# Install the system files found in the _system directory
ADD $labdir/$imagedir/sys_tar/sys.tar /
ADD $labdir/sys_$lab.tar.gz /

RUN useradd -ms /bin/bash $user_name
RUN echo "$user_name:$password" | chpasswd
RUN adduser $user_name sudo

USER $user_name
ENV HOME /home/$user_name
ADD $labdir/$imagedir/home_tar/home.tar $HOME
RUN rm -f $HOME/home.tar
ADD $labdir/$lab.tar.gz $HOME

USER root
CMD ["/bin/bash", "-c", "exec /sbin/init --log-target=journal 3>&1"]

